# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['CloudInit.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'loguru',
        'netifaces',
        'requests',
        'psutil',
        'NICManager',
        'NICManager.NCManage',
        'NICManager.NCConfig',
        'VMUploader',
        'VMUploader.VMStatus',
        'VMUploader.HWStatus',
        'VMUploader.VMPowers',
        'CoreManage',
        'CoreManage.CoreConfig',
        'CoreManage.CoreManage',
        'CoreManage.AutoUpdate',
        'CoreManage.DiskExtend',
        'CoreManage.PowerSetup',
        'OSPlatform',
        'OSPlatform.PlatformFactory',
        'OSPlatform.PlatformBase',
        'OSPlatform.PlatformLinux',
        'OSPlatform.PlatformMacOS',
        'OSPlatform.PlatformWindows',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CloudInit',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
